name: Canisters test suite run on any push
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run canister test suite
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bash scripts/install-dependencies.sh

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run canister test suite
        run: bash scripts/run-canister-test-suite.sh
