name: Canisters test suite run on any push except main
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run canister test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run suite in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bash scripts/run_canister_test_suite.sh
          env: |
            POCKET_IC_BIN=/workspaces/yral-backend-canister/pocket-ic
