name: Release and submit proposal
on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Publish canister artifacts and send upgrade proposals
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    env:
      NEURON_ID: 4de673e9cd7a1339afea6523a5f227d25e9d739ff52635ac86dbdb0447ae106a

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run release workflow in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bash scripts/ci/release_and_submit_proposals.sh
          env: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
            HOT_OR_NOT_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY=${{ secrets.HOT_OR_NOT_SNS_PROPOSAL_SUBMISSION_IDENTITY_PRIVATE_KEY }}
            VERSION=${{ github.ref_name }}
            NEURON_ID=${{ env.NEURON_ID }}
            GITHUB_REPOSITORY=${{ github.repository }}
