name: Add PR to project
on:
  pull_request:
    types:
      - ready_for_review
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Uses the [actions/create-github-app-token](https://github.com/marketplace/actions/create-github-app-token) action to generate an installation access token for your app from the app ID and private key. The installation access token is accessed later in the workflow as `${{ steps.generate-token.outputs.token }}`.
      #
      # Replace `APP_ID` with the name of the configuration variable that contains your app ID.
      #
      # Replace `APP_PEM` with the name of the secret that contains your app private key.
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.PROJECT_WORKFLOW_APP_FOR_PR_ADDITION_TO_GITHUB_PROJECT_APP_ID }}
          private-key: ${{ secrets.PROJECT_WORKFLOW_APP_FOR_PR_ADDITION_TO_GITHUB_PROJECT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Add PR to project in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bash scripts/add_pr_to_project.sh
          env: |
            GH_TOKEN=${{ steps.generate-token.outputs.token }}
            ORGANIZATION=${{ github.repository_owner }}
            PROJECT_NUMBER=12
            PR_ID=${{ github.event.pull_request.node_id }}
            STATUS_NAME=Status
            STATUS_OPTION_NAME=Todo
